name: Build Docker

on:
  workflow_dispatch: 

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build the Docker image from the provided Dockerfile
    - name: Build Docker image
      run: |
        docker build -t node-sqitch:latest node-sqitch/