name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4 

    # Pull the public Docker image
    - name: Pull Docker image
      run: docker pull pyramation/pstricks-latex:latest

    # Compile the LaTeX file using the built Docker image
    - name: Build LaTeX PDF
      run: |
        docker run --rm \
          -v "${{ github.workspace }}/tex:/usr/src" \
          pyramation/pstricks-latex \
          sh -c "\
            export PATH=/usr/bin:\$PATH && \
            latex test.tex && \
            latex test.tex && \
            dvips test.dvi -o test.ps && \
            ps2pdf test.ps test.pdf"

    # Upload the compiled PDF as an artifact
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test.pdf
        path: tex/test.pdf

    - name: Upload Log File on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test.log
        path: tex/test.log