name: Build Docker

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Build the Docker image from the provided Dockerfile
    - name: Build Docker image
      run: |
        docker build -t latex-build:latest latex/

    # Compile the LaTeX file using the built Docker image
    - name: Build LaTeX PDF
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/tex:/usr/src \
          latex-build:latest \
          pdflatex test.tex

    # Upload the compiled PDF as an artifact
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test.pdf
        path: tex/test.pdf
